version: "2"

issues:
  max-same-issues: 50

formatters:
  enable:
    - gofumpt
    - goimports
    - golines

  settings:
    goimports:
      local-prefixes: github.com/danrneal/gtd.nvim

    golines:
      max-len: 120

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    staticcheck:
      checks:
        - all
        - -ST1000

  exclusions:
    warn-unused: true
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
